// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gfawlwjrirqvtdwuzqmm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdmYXdsd2pyaXJxdnRkd3V6cW1tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4ODUwODEsImV4cCI6MjA2ODQ2MTA4MX0.o9gOAVarEgl0r9sSdKvSrcN2h43IZY_QN2OOfg2w1NY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});